# syntax=docker/dockerfile:1

# ---- Build stage: static musl binary ----
# rust:1-alpine's host target is x86_64-unknown-linux-musl, so `cargo build`
# produces a fully static binary with no glibc coupling to DSM's older libc.
FROM rust:1-alpine AS build
RUN apk add --no-cache musl-dev
WORKDIR /src

# Copy manifests + source. (Cargo.lock is generated by `cargo build`/`test`.)
COPY Cargo.toml Cargo.lock ./
COPY src ./src

# Build the release binary. reqwest uses rustls (no OpenSSL), so the result
# links cleanly against musl with no dynamic C deps.
RUN cargo build --release && cp target/release/hi5bot /hi5bot

# ---- Runtime stage: minimal, non-root, with CA roots + tzdata ----
FROM alpine:3
RUN apk add --no-cache ca-certificates tzdata \
 && addgroup -S app && adduser -S app -G app \
 && mkdir -p /app/data && chown -R app:app /app
WORKDIR /app
COPY --from=build /hi5bot /app/hi5bot

# Run as non-root; the data dir is the single mounted volume.
USER app
ENV HI5BOT_DATA_DIR=/app/data \
    TZ=America/Toronto \
    RUST_LOG=info

# Long-running daemon; it self-schedules the 15:30 America/Toronto wake.
ENTRYPOINT ["/app/hi5bot"]
